# Learn more: https://docs.docker.com/compose/reference/
#
# Build images:   docker-compose build
# Start app:      docker-compose up borda
# Start database: docker-compose up db
# Stop all:       docker-compose down (add -v to wipe db)
#
version: "3.9"
services:
  borda:
    image: borda
    container_name: borda
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  # import-tasks:
  #   image: borda:latest
  #   build:
  #     context: .
  #   environment:
  #     - .env
  #   depends_on:
  #     - db
  #   command: ["import-tasks", 
  #     "--token", "${GITHUB_ACCESS_TOKEN}",
  #     "--repo", "${TASK_REPOSITORY_URL}",
  #     "--db", "${DATABASE_URL}"]

  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      # https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker
      - ./.postgres/data:/var/lib/postgresql/data:Z
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"

  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    depends_on:
      - db

#networks:
#  backend:
#
#volumes:
#  db-data: